FROM node:22-alpine AS builder
WORKDIR /worker
COPY worker/package*.json ./
RUN npm ci
COPY worker/ .
RUN npm run build

FROM node:22-alpine
WORKDIR /worker
COPY --from=builder /worker/dist ./dist
COPY --from=builder /worker/node_modules ./node_modules
COPY --from=builder /worker/package.json ./
CMD ["node", "dist/index.js"]
